name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Deno 2
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Use latest Deno 2.x

      # Cache dependencies (optional)
      - name: Cache Deno modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}

      # Install esbuild by caching the build script
      - name: Cache esbuild
        run: deno cache build.ts

      # Build the project using Deno and esbuild with required permissions
      - name: Build project
        run: deno run --allow-read --allow-write --allow-net --allow-env --allow-run build.ts
        env:
          PUBLIC_URL: .

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true # Ensures a clean gh-pages branch
